name: Build catalog.json for comparison UI

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**'
      - 'scripts/generate_catalog_json.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Generate compare/catalog.json
        run: |
          python scripts/generate_catalog_json.py
      - name: Commit artifact
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add compare/catalog.json
            git commit -m "build(compare): regenerate catalog.json"
            git push
          else
            echo "No changes"
