name: Weekly Stars Refresh

on:
  schedule:
    - cron: '0 5 * * 1' # Mondays 05:00 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Refresh stars and last commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/refresh_stars.py
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/frameworks.csv
            git commit -m "chore(data): weekly star + last_commit refresh"
            git push
          else
            echo "No changes to commit"
          fi
