name: Weekly Stars Refresh (multi CSV)

on:
  schedule:
    - cron: '0 5 * * 1' # Mondays 05:00 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Refresh stars for frameworks + computer_use
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/refresh_csv.py --paths data/frameworks.csv data/computer_use.csv
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/frameworks.csv data/computer_use.csv
            git commit -m "chore(data): weekly star/last_update refresh (multi-CSV)"
            git push
          else
            echo "No changes to commit"
          fi